create database QuanAo_DA
go
use QuanAo_DA
go


CREATE TABLE NHANVIEN
(
	MANV INT IDENTITY(1,1) PRIMARY KEY , --identity(1,1) 1 đầu là mã đầu tiên, 1 sau là bước nhảy                                       
	HOTENNV NVARCHAR(30),
	NGSINH DATE CHECK (GETDATE()>NGSINH),
	DCHI NVARCHAR(50),
	GIOITINH BIT DEFAULT 1 NOT NULL,
	LUONG INT,
	USERNAME NVARCHAR(24) NOT NULL,
	PASSWORD NVARCHAR(24) NOT NULL,
	TRANGTHAI  BIT DEFAULT 1 NOT NULL
)
GO
CREATE TABLE KHACHHANG
( 
	MAKH INT IDENTITY(1,1) PRIMARY KEY,
	TENKH NVARCHAR(30) NOT NULL,
	SDT CHAR(10) NOT NULL

)
GO
CREATE TABLE SANPHAM
(
	MASP INT IDENTITY(1,1) PRIMARY KEY,
	TENSP NVARCHAR(MAX) NOT NULL,
	MALOAI INT ,
	DONGIA DECIMAL NOT NULL,
	SOLUONGTON INT,
	MASX INT,
	HINHANH NVARCHAR (MAX),
	TRANGTHAI bit DEFAULT 1 NOT NULL
)
GO

CREATE TABLE CHITIETSANPHAM
(
	MASP INT,
	SIZE NVARCHAR(20),
	MAU NVARCHAR(20)
	PRIMARY KEY(MASP, MAU, SIZE)

)
GO
CREATE TABLE LOAISANPHAM
(
	MALOAI INT IDENTITY(1,1) PRIMARY KEY,
	TENLOAI NVARCHAR(20) NOT NULL
)
GO
CREATE TABLE NHASANXUAT
(
	MASX INT IDENTITY(1,1) PRIMARY KEY,
	TENNHASX NVARCHAR(30) NOT NULL
)
GO
CREATE TABLE HOADON
(
	MAHD INT IDENTITY(1,1) PRIMARY KEY,
	MAKH INT ,
	NGAYLAP DATETIME DEFAULT (GETDATE()),
	MANV INT,
	TONGTIEN DECIMAL,
	TRANGTHAI BIT DEFAULT 1 NOT NULL
)
GO
CREATE TABLE CHITIETHOADON
(
	MAHD INT,
	MASP INT,
	SOLUONG INT,
	DONGIA DECIMAL
CONSTRAINT PK_CHITIETHOADON PRIMARY KEY (MAHD,MASP)
)
GO



--bang LOAISANPHAM
INSERT INTO LOAISANPHAM VALUES(N'Quần dài')
INSERT INTO LOAISANPHAM VALUES(N'Quần ngắn')
INSERT INTO LOAISANPHAM VALUES(N'Đầm')
INSERT INTO LOAISANPHAM VALUES(N'Váy')
INSERT INTO LOAISANPHAM VALUES(N'Áo thun')
INSERT INTO LOAISANPHAM VALUES(N'Áo sơ mi')
INSERT INTO LOAISANPHAM VALUES(N'Áo khoác')
GO

--BANG NHASANXUAT
INSERT INTO NHASANXUAT VALUES(N'jeanshunter');
INSERT INTO NHASANXUAT VALUES(N'Gumac');
INSERT INTO NHASANXUAT VALUES(N'Sphynx');
INSERT INTO NHASANXUAT VALUES(N'May Gia Huỳnh');
INSERT INTO NHASANXUAT VALUES(N'Mende');
GO
--BANG KHACHHANG
INSERT INTO KHACHHANG VALUES(N'Nguyễn Thị Bé','0856789578');
INSERT INTO KHACHHANG VALUES(N'Lê Hoàng Nam','0987654722');
INSERT INTO KHACHHANG VALUES(N'Trần Thị Chiêu','0529649039');
INSERT INTO KHACHHANG VALUES(N'Mai Thị Quế Anh','0953764812');
INSERT INTO KHACHHANG VALUES(N'Lê Văn Sang','0678536965');
INSERT INTO KHACHHANG VALUES(N'Nguyễn Thị Thanh Trà','0542907425');
GO
--BANG NHANVIEN
INSERT INTO NHANVIEN VALUES(N'Nguyễn Bảo Hùng','09/30/1990',N'98 Huỳnh Văn Bách, Phú Nhuận,Tp.HCM',1,'6000000',N'baohung','12345',1);
INSERT INTO NHANVIEN VALUES(N'Phan Văn Nghĩa','07/12/1998',N'97 Điện Biên Phủ ,Bình Thạnh,TP.HCM',1,'7500000',N'vannghia','12345',1);
INSERT INTO NHANVIEN VALUES(N'Lê Văn Bo','03/05/1997',N'29 Bạch Đằng,Tân Bình,TP.HCM',1,'5000000',N'vanbo','12345',1);
INSERT INTO NHANVIEN VALUES(N'Trần Thị Hậu','08/03/1870',N'Hồ Văn Huê, Phú Nhuận,TP.HCM',0,'6000000',N'thihau','12345',1);
INSERT INTO NHANVIEN VALUES(N'Nguyễn Thị Bảo Trân','06/22/1988',N'63 Trần Huy Liễu, Phú Nhuận,TP.HCM',0,'5500000',N'baotran','12345',1);
INSERT INTO NHANVIEN VALUES(N'Nguyễn Trần Bảo Nghi','07/04/1995',N'56 Thích Quảng Đức, Phú Nhuận,TP.HCM',0,'6400000',N'baonghi','12345',1);
GO


--BANG HOADON
INSERT INTO HOADON VALUES('1','02/28/2019 00:00:00','1','1628000',1);
INSERT INTO HOADON VALUES('2','03/03/2019 00:00:00','2','956000',1);
INSERT INTO HOADON VALUES('1','03/16/2019 00:00:00','2','900000',1);
INSERT INTO HOADON VALUES('4','03/16/2019 00:00:00','2','2000000',1);
INSERT INTO HOADON VALUES('3','03/25/2019 00:00:00','3','1200000',1);
INSERT INTO HOADON VALUES('5','05/15/2019 00:00:00','1','1900000',1);
INSERT INTO HOADON VALUES('1','06/01/2019 00:00:00','3','1200000',1);
INSERT INTO HOADON VALUES('2','09/20/2019 00:00:00','4','514000',1);
INSERT INTO HOADON VALUES('5','11/03/2019 00:00:00','4','1365000',1);
INSERT INTO HOADON VALUES('4','12/12/2019 00:00:00','5','700000',1);
GO
--CHITIETHOADON
INSERT INTO CHITIETHOADON VALUES('1','6','3','220000');
INSERT INTO CHITIETHOADON VALUES('1','69','2','320000');
INSERT INTO CHITIETHOADON VALUES('1','91','2','164000');
INSERT INTO CHITIETHOADON VALUES('2','40','4','239000');
INSERT INTO CHITIETHOADON VALUES('3','21','2','320000');
INSERT INTO CHITIETHOADON VALUES('3','9','1','260000');
INSERT INTO CHITIETHOADON VALUES('4','79','5','400000');
INSERT INTO CHITIETHOADON VALUES('5','86','3','290000');
INSERT INTO CHITIETHOADON VALUES('5','65','1','330000');
INSERT INTO CHITIETHOADON VALUES('6','18','2','225000');
INSERT INTO CHITIETHOADON VALUES('6','53','5','200000');
INSERT INTO CHITIETHOADON VALUES('6','61','3','150000');
INSERT INTO CHITIETHOADON VALUES('7','53','3','200000');
INSERT INTO CHITIETHOADON VALUES('7','100','4','150000');
INSERT INTO CHITIETHOADON VALUES('8','31','1','275000');
INSERT INTO CHITIETHOADON VALUES('8','42','1','239000');
INSERT INTO CHITIETHOADON VALUES('9','28','7','195000');
INSERT INTO CHITIETHOADON VALUES('10','1','6','250000');
INSERT INTO CHITIETHOADON VALUES('10','88','2','350000');
GO

--SANPHAM
INSERT INTO SANPHAM VALUES(N'Flare jeans','1','250000','20','1','flare.png',1);
INSERT INTO SANPHAM VALUES(N'Mia jeans','1','260000','20','1','mia.png',1);
INSERT INTO SANPHAM VALUES(N'Lisa Jeans','1','250000','20','1','lisa.png',1);
INSERT INTO SANPHAM VALUES(N'Long Jeans-850','1','320000','20','1','longjean-850.png',1);
INSERT INTO SANPHAM VALUES(N'Long Jeans-7507','1','320000','20','1','longjean-7507.png',1);
INSERT INTO SANPHAM VALUES(N'Lya jeans','1','220000','20','1','lya-be.jpg',1);
INSERT INTO SANPHAM VALUES(N'Zoe jeans','1','260000','20','1','zoe.jpg',1);
INSERT INTO SANPHAM VALUES(N'Baggy Vải','1','150000','20','1','baggyvai.jpg',1);
INSERT INTO SANPHAM VALUES(N'Roise jeans','1','260000','20','1','rose.jpg',1);
INSERT INTO SANPHAM VALUES(N'Hana jeans','1','255000','20','1','hana.jpg',1);
INSERT INTO SANPHAM VALUES(N'Kaki Trousers','1','300000','20','1','kaki.jpg',1);
INSERT INTO SANPHAM VALUES(N'Caro pants','1','175000','20','1','caro.jpg',1);
INSERT INTO SANPHAM VALUES(N'Quần ba sọc','1','150000','20','1','3soc.jpg',1);
INSERT INTO SANPHAM VALUES(N'Jeans bó - 9223','1','240000','20','1','jean-9223.jpg',1);
INSERT INTO SANPHAM VALUES(N'Skinny jeans rách gối','1','195000','20','1','rach-goi.jpg',1);
INSERT INTO SANPHAM VALUES(N'Linen Culttens','1','180000','20','1','linen.jpg',1);
INSERT INTO SANPHAM VALUES(N'Quần dài loang','1','290000','20','1','loangdai.jpeg',1);
INSERT INTO SANPHAM VALUES(N'Ống rộng sọc','1','225000','20','1','ong-rong-soc.jpg',1);
INSERT INTO SANPHAM VALUES(N'Bobby jeans','1','320000','20','1','bobby.jpg',1);
INSERT INTO SANPHAM VALUES(N'Bion Pants','1','300000','20','1','bion.jpg',1);
INSERT INTO SANPHAM VALUES(N'Ocean jeans','1','320000','20','1','ocean.jpg',1);
INSERT INTO SANPHAM VALUES(N'Miru Pants','1','320000','20','1','miru.jpg',1);
INSERT INTO SANPHAM VALUES(N'Gody pants','1','275000','20','1','gody-pants.jpg',1);
INSERT INTO SANPHAM VALUES(N'Cullottes Jeans','1','320000','20','1','cullottes-jeans.JPG',1);
INSERT INTO SANPHAM VALUES(N'Simply Short','2','180000','20','1','simply.jpg',1);
INSERT INTO SANPHAM VALUES(N'Short Jeans','2','180000','20','1','shortjeans.jpg',1);
INSERT INTO SANPHAM VALUES(N'Quần ngắn vải dù','2','300000','20','1','short-du.jpg',1);
INSERT INTO SANPHAM VALUES(N'Short vạt chéo - Pure short','2','195000','20','1','short-cheo.jpg',1);
INSERT INTO SANPHAM VALUES(N'Unicorn short','2','170000','20','1','unicorn.jpg',1);
INSERT INTO SANPHAM VALUES(N'Vico Short','2','300000','20','1','vico-short.jpg',1);
INSERT INTO SANPHAM VALUES(N'Ali Short','2','275000','20','1','ali-short.jpg',1);
INSERT INTO SANPHAM VALUES(N'Moti Short ','2','200000','20','1','moti-short.jpg',1);
INSERT INTO SANPHAM VALUES(N'Mochi short','2','210000','20','1','mochi-short.jpg',1);
INSERT INTO SANPHAM VALUES(N'Váy đầm nữ trắng hai dây tay phồng','3','150000','20','2','dam-tay-phong.png',1);
INSERT INTO SANPHAM VALUES(N'Set váy yếm kẻ vintage','3','200000','20','2','yem-vintage.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm ôm nữ GUMAC cổ U','3','420000','20','2','o-U.png',1);
INSERT INTO SANPHAM VALUES(N'Váy đầm nữ dáng xòe tay lưới dài','3','150000','20','2','tay-luoi-dai.png',1);
INSERT INTO SANPHAM VALUES(N'Váy Babydoll Nữ Dài Tay Cổ Sen','3','150000','20','2','babbydoll-co-sen.png',1);
INSERT INTO SANPHAM VALUES(N'Váy đen body tay ngực phối trắng','3','250000','20','2','body-den.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm kẻ hai dây','3','239000','20','2','ke-hai-day.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm suông milky','3','429000','20','2','milky.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm trắng hoa vàng','3','239000','20','2','trang-hoa-vang.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm pink đuôi cá','3','429000','20','2','pink-duoi-ca.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm caro vitage','3','429000','20','2','caro.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm miki tay bèo','3','320000','20','2','miki-tay-beo.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm bẹt vai nhún','3','495000','20','2','bet-tay-nhun.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm peplum tay dài','3','590000','20','2','peplum-tay-dai.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm 2 dây đai eo','3','590000','20','2','2-day-dai-eo.png',1);
INSERT INTO SANPHAM VALUES(N'Váy công chúa trể vai','3','133000','20','2','congchua.png',1);
INSERT INTO SANPHAM VALUES(N'Váy Hai Dây Kẻ Ô','3','139000','20','2','ke-o.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm thiết kế trắng dài tay','3','139000','20','2','trang-tay-dai.png',1);
INSERT INTO SANPHAM VALUES(N'Váy xếp ly cổ bèo','3','150000','20','2','xep-li-co-beo.png',1);
INSERT INTO SANPHAM VALUES(N'Set váy Hot Gin','3','200000','20','2','gin.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm Baby doll','3','150000','20','2','babydoll.png',1);
INSERT INTO SANPHAM VALUES(N' Đầm Baby Doll Summer','3','250000','20','2','summer.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm bigsize trắng cổ bèo xoè nhẹ','3','200000','20','2','bigsize.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm xòe tay phồng rớt đi tiệc','3','390000','20','2','tay-phong.png',1);
INSERT INTO SANPHAM VALUES(N'Đầm tay phồng phối trắng','3','150000','20','2','phong-trang.png',1);
INSERT INTO SANPHAM VALUES(N'Chân Váy Chữ A Xếp Ly Lưng Cao','4','199000','20','2','vay-a.png',1);
INSERT INTO SANPHAM VALUES(N'Chân váy a xẻ cạnh','4','170000','20','2','ulzzang.png',1);
INSERT INTO SANPHAM VALUES(N'Chân váy kaki ôm lưng cao','4','150000','20','2','kaki-om.png',1);
INSERT INTO SANPHAM VALUES(N'Váy Nữ Ulzzang Cạp Chun','4','175000','20','2','ulzzang-chun.png',1);
INSERT INTO SANPHAM VALUES(N'Chân váy xếp li dài','4','150000','20','2','xep-li.png',1);
INSERT INTO SANPHAM VALUES(N'Chân váy xòe vạt lệch phối đen trắng','4','150000','20','2','xoe-vat-let.png',1);
INSERT INTO SANPHAM VALUES(N' Áo thun Toy brown','5','330000','20','3','toy-brown.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo BadRabbit Rabbies','5','380000','20','3','rabbies.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo BadRabbit Masker','5','330000','20','3','masker.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo BadRabbit Iconic Camo','5','320000','20','3','iconic-camo.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo BadRabbit Pocky','5','320000','20','3','pocky.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo thun Twenti','5','150000','20','3','twenti-tee.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo TSUN xương rồng','5','320000','20','3','cactus-tsun.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo TSUN dưa hấu','5','320000','20','3','wtml-tsun.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo TSUN candy','5','320000','20','3','candy-tsun.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo thun Polo basic','5','360000','20','3','polo-basic.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo thun tay ngắn thêu','5','150000','20','3','theu.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo phông nelly- chillhood','5','150000','20','3','nelly.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo thun Nelly-poormon','5','130000','20','3','poormon.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo thun cộc tay Fukuoka','5','154000','20','3','fukuoka.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo thun Levent ','5','400000','20','3','levent.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo thun badrabbit power','5','340000','20','3','power.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo thun Ice-Cream ','5','334000','20','3','ice-cream.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo thun hoa CLICK','5','335000','20','3','hoa.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo thun mặt trăng ','6','360000','20','4','moon.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo sơ mi trơn cổ vest','6','129000','20','5','somi-co-tron.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo sơ mi Logo MND','6','265000','20','5','mnd-xanh.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo sơ mi mende thunder shirt','6','290000','20','5','thunder-shirt.jpeg',1);
INSERT INTO SANPHAM VALUES(N'Áo sơ mi mende cartoon shirt','6','350000','20','5','cartoon.jpeg',1);
INSERT INTO SANPHAM VALUES(N'Áo sơ mi mende dark sky','6','350000','20','5','dark-sky.jpeg',1);
INSERT INTO SANPHAM VALUES(N'Hoodie zip twenty  xám camo','7','260000','20','4','zip-twenti.jpg',1);
INSERT INTO SANPHAM VALUES(N'Hoodie Smiley logo missout','7','520000','20','4','smiley.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo khoác Aness ','7','164000','20','4','aness.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo khoác Banana','7','157000','20','4','banana.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo bomber face','7','189000','20','4','bomber-face.jpg',1);
INSERT INTO SANPHAM VALUES(N'Jacket P logo sau','7','495000','20','4','plogosau.png',1);
INSERT INTO SANPHAM VALUES(N'Jacket icon ant','7','400000','20','4','coach-jacket-icon-ant_black.jpg',1);
INSERT INTO SANPHAM VALUES(N'jacket bad rabbit','7','440000','20','4','jacket-bad.jpg',1);
INSERT INTO SANPHAM VALUES(N'hoddie click','7','455000','20','4','hoddie-click.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo khoác dây kéo CLK','7','455000','20','4','keo-click.jpg',1);
INSERT INTO SANPHAM VALUES(N'Blazer trơn','7','220000','20','4','blazer.jpg',1);
INSERT INTO SANPHAM VALUES(N'Áo khoác nút nón rộng','7','150000','20','4','non-rong.jpg',1);

GO

--CHITIETSANPHAM
INSERT INTO CHITIETSANPHAM VALUES('1','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('1','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('1','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('2','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('2','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('2','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('3','S',N'xanh')
INSERT INTO CHITIETSANPHAM VALUES('3','M',N'xanh')
INSERT INTO CHITIETSANPHAM VALUES('3','L',N'xanh')
INSERT INTO CHITIETSANPHAM VALUES('4','S',N'xanh nhạt')
INSERT INTO CHITIETSANPHAM VALUES('4','M',N'xanh nhạt')
INSERT INTO CHITIETSANPHAM VALUES('4','L',N'xanh nhạt')
INSERT INTO CHITIETSANPHAM VALUES('5','S',N'xanh bạc')
INSERT INTO CHITIETSANPHAM VALUES('5','M',N'xanh bạc')
INSERT INTO CHITIETSANPHAM VALUES('5','L',N'xanh bạc')
INSERT INTO CHITIETSANPHAM VALUES('6','S',N'be')
INSERT INTO CHITIETSANPHAM VALUES('6','M',N'be')
INSERT INTO CHITIETSANPHAM VALUES('6','L',N'be')
INSERT INTO CHITIETSANPHAM VALUES('6','XL',N'be')
INSERT INTO CHITIETSANPHAM VALUES('6','S',N'xanh bạc')
INSERT INTO CHITIETSANPHAM VALUES('6','M',N'xanh bạc')
INSERT INTO CHITIETSANPHAM VALUES('6','L',N'xanh bạc')
INSERT INTO CHITIETSANPHAM VALUES('6','XL',N'xanh bạc')
INSERT INTO CHITIETSANPHAM VALUES('7','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('7','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('7','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('7','XL',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('8','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('8','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('8','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('9','S',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('9','M',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('9','L',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('9','XL',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('10','S',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('10','M',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('10','L',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('11','S',N'be')
INSERT INTO CHITIETSANPHAM VALUES('11','M',N'be')
INSERT INTO CHITIETSANPHAM VALUES('11','L',N'be')
INSERT INTO CHITIETSANPHAM VALUES('11','XL',N'be')
INSERT INTO CHITIETSANPHAM VALUES('12','S',N'vàng')
INSERT INTO CHITIETSANPHAM VALUES('12','M',N'vàng')
INSERT INTO CHITIETSANPHAM VALUES('12','L',N'vàng')
INSERT INTO CHITIETSANPHAM VALUES('12','S',N'xanh ')
INSERT INTO CHITIETSANPHAM VALUES('12','M',N'xanh ')
INSERT INTO CHITIETSANPHAM VALUES('12','L',N'xanh ')
INSERT INTO CHITIETSANPHAM VALUES('13','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('13','F',N'xanh ')
INSERT INTO CHITIETSANPHAM VALUES('14','S',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('14','M',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('14','L',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('15','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('15','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('15','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('16','F',N'be')
INSERT INTO CHITIETSANPHAM VALUES('16','F',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('16','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('17','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('17','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('17','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('18','S',N'tím')
INSERT INTO CHITIETSANPHAM VALUES('18','M',N'tím')
INSERT INTO CHITIETSANPHAM VALUES('18','L',N'tím')
INSERT INTO CHITIETSANPHAM VALUES('18','S',N'xanh lá')
INSERT INTO CHITIETSANPHAM VALUES('18','M',N'xanh lá')
INSERT INTO CHITIETSANPHAM VALUES('18','L',N'xanh lá')
INSERT INTO CHITIETSANPHAM VALUES('19','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('19','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('19','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('19','S',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('19','L',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('20','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('20','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('20','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('21','S',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('21','M',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('21','XL',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('21','S',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('21','M',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('21','L',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('22','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('22','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('22','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('23','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('23','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('23','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('24','S',N'xanh ')
INSERT INTO CHITIETSANPHAM VALUES('24','M',N'xanh ')
INSERT INTO CHITIETSANPHAM VALUES('24','L',N'xanh')
INSERT INTO CHITIETSANPHAM VALUES('25','M',N'be')
INSERT INTO CHITIETSANPHAM VALUES('25','L',N'be')
INSERT INTO CHITIETSANPHAM VALUES('25','S',N'be')
INSERT INTO CHITIETSANPHAM VALUES('26','S',N'xanh')
INSERT INTO CHITIETSANPHAM VALUES('26','M',N'xanh ')
INSERT INTO CHITIETSANPHAM VALUES('26','L',N'xanh ')
INSERT INTO CHITIETSANPHAM VALUES('27','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('27','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('27','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('28','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('28','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('28','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('29','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('29','F',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('29','F',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('30','F',N'bạc')
INSERT INTO CHITIETSANPHAM VALUES('30','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('30','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('30','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('31','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('31','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('31','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('32','S',N'Vàng')
INSERT INTO CHITIETSANPHAM VALUES('32','M',N'Vàng')
INSERT INTO CHITIETSANPHAM VALUES('32','L',N'Vàng')
INSERT INTO CHITIETSANPHAM VALUES('33','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('33','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('33','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('34','F',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('35','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('35','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('35','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('36','F',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('37','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('38','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('39','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('39','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('39','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('40','S',N'xanh')
INSERT INTO CHITIETSANPHAM VALUES('40','M',N'xanh')
INSERT INTO CHITIETSANPHAM VALUES('40','L',N'xanh')
INSERT INTO CHITIETSANPHAM VALUES('41','F',N'đỏ')
INSERT INTO CHITIETSANPHAM VALUES('42','S',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('42','M',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('42','l',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('43','F',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('44','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('44','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('44','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('45','M',N'vàng')
INSERT INTO CHITIETSANPHAM VALUES('45','L',N'vàng')
INSERT INTO CHITIETSANPHAM VALUES('46','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('46','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('46','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('47','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('47','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('48','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('48','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('48','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('49','F',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('50','S',N'đỏ')
INSERT INTO CHITIETSANPHAM VALUES('50','M',N'đỏ')
INSERT INTO CHITIETSANPHAM VALUES('50','L',N'đỏ')
INSERT INTO CHITIETSANPHAM VALUES('51','F',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('52','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('52','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('52','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('53','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('53','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('53','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('54','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('54','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('54','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('55','F',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('56','L',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('56','XXL',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('57','M',N'nude')
INSERT INTO CHITIETSANPHAM VALUES('57','L',N'nude')
INSERT INTO CHITIETSANPHAM VALUES('57','XL',N'nude')
INSERT INTO CHITIETSANPHAM VALUES('58','S',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('58','M',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('58','L',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('59','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('59','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('59','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('60','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('60','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('60','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('61','F',N'nude')
INSERT INTO CHITIETSANPHAM VALUES('62','F',N'nude')
INSERT INTO CHITIETSANPHAM VALUES('63','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('64','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('65','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('65','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('65','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('66','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('66','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('66','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('67','S',N'nude')
INSERT INTO CHITIETSANPHAM VALUES('67','M',N'nude')
INSERT INTO CHITIETSANPHAM VALUES('67','L',N'nude')
INSERT INTO CHITIETSANPHAM VALUES('68','S',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('68','M',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('68','L',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('69','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('69','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('69','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('70','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('70','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('70','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('71','S',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('71','M',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('71','L',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('72','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('72','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('72','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('73','S',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('73','M',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('73','L',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('74','S',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('74','M',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('74','L',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('75','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('75','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('75','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('76','S',N'cam')
INSERT INTO CHITIETSANPHAM VALUES('76','M',N'cam')
INSERT INTO CHITIETSANPHAM VALUES('76','L',N'cam')
INSERT INTO CHITIETSANPHAM VALUES('77','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('77','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('77','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('78','S',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('78','M',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('78','L',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('79','S',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('79','M',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('79','L',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('80','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('80','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('80','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('81','S',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('81','M',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('81','L',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('82','S',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('82','M',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('82','L',N'hồng')
INSERT INTO CHITIETSANPHAM VALUES('83','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('83','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('83','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('84','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('84','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('84','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('85','S',N'xanh')
INSERT INTO CHITIETSANPHAM VALUES('85','M',N'xanh ')
INSERT INTO CHITIETSANPHAM VALUES('85','L',N'xanh ')
INSERT INTO CHITIETSANPHAM VALUES('86','S',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('86','M',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('86','L',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('87','S',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('87','M',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('87','L',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('88','S',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('88','M',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('88','L',N'xanh đậm')
INSERT INTO CHITIETSANPHAM VALUES('89','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('90','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('91','F',N'xanh lá')
INSERT INTO CHITIETSANPHAM VALUES('92','F',N'trắng')
INSERT INTO CHITIETSANPHAM VALUES('93','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('94','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('95','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('96','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('97','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('98','F',N'đen')
INSERT INTO CHITIETSANPHAM VALUES('99','F',N'nude')
INSERT INTO CHITIETSANPHAM VALUES('100','F',N'đen')
GO

ALTER TABLE SANPHAM ADD
CONSTRAINT FK_SANPHAM_LOAISP FOREIGN KEY (MALOAI) REFERENCES LOAISANPHAM(MALOAI)
go
ALTER TABLE SANPHAM ADD
CONSTRAINT FK_SANPHAM_NHASANXUAT FOREIGN KEY (MASX) REFERENCES NHASANXUAT(MASX)
GO
ALTER TABLE CHITIETSANPHAM ADD
CONSTRAINT FK_CHITIETSANPHAM_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
GO
ALTER TABLE HOADON ADD
CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
go
ALTER TABLE HOADON ADD
CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
GO
ALTER TABLE CHITIETHOADON ADD
CONSTRAINT FK_CHITIETHOADON_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
go
ALTER TABLE CHITIETHOADON ADD
CONSTRAINT FK_CHITIETHOADON_SANPHAM FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
GO

CREATE PROCEDURE RPTHOADON(@MAHD INT)
AS
BEGIN
	 SELECT HOADON.MAHD, HOADON.NGAYLAP, NHANVIEN.HOTENNV, KHACHHANG.TENKH, HOADON.TONGTIEN, SANPHAM.TENSP,CHITIETHOADON.SOLUONG,CHITIETHOADON.DONGIA
	 FROM HOADON INNER JOIN CHITIETHOADON ON HOADON.MAHD = CHITIETHOADON.MAHD INNER JOIN SANPHAM ON CHITIETHOADON.MASP=SANPHAM.MASP INNER JOIN NHANVIEN ON HOADON.MANV = NHANVIEN.MANV INNER JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
	 WHERE HOADON.MAHD = @MAHD
END


